export PATH="$PATH:/Volumes/macOSXHighSierra/Applications"
export PATH="$PATH:/Volumes/macOSXHighSierra/Development/flutter/bin"
export PATH="$PATH:~/homebrew/bin"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"
export LDFLAGS="$LDFLAGS -L/usr/local/opt/libffi/lib"
export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/libffi/include"
